### ISSUE TITLE
-webkit-tap-highlight-color:

### ISSUE THREAD

**Issue by lemmingz** [Schepp/CSS-Prefix-Spawner#2]
Hi,
auf jeden Fall ein sehr nützliches Tool, grade da Opera ja auch mal anfängt ein paar CSS3-Schönheiten zu unterstützen. 

Mir ist nur grade aufgefallen, dass aus -webkit-tap-highlight-color dann auch noch -o-tap-highlight-color und -moz-tap-highlight-color gemacht werden. Ist zwar nicht schlimm, aber auch nicht sinnvoll.

mfg

**Comment by Schepp** [comment]
Ja, der Effekt bleibt nicht aus, da das Tool ja keine wirkliche CSS3-Eigenschaften erkennt. Dafür hat es aber eben auch kein Problem mit Eigenschaften, die vielleicht erst in Zukunft erfunden werden. Und schaden tut es ja auch nicht :)
